### ISSUE TITLE
Please support com.amazonaws.sdk.disableCertChecking

### ISSUE THREAD

**Issue by etspaceman** [aws/aws-sdk-java-v2#1230]
According to https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#11-client-creation-defaults, the V2 SDK no longer supports the `com.amazonaws.sdk.disableCertChecking` system property usage. 

This parameter was a key item when interacting with [Localstack](https://github.com/localstack/localstack/issues/893), which has served as the primary local mock for Kinesis in the OSS community. This is because Localstack randomly generates self-signed certificates. It is not possible to interact with those certificates without disabling the validation of them.

It is possible to continue to leverage Localstack with the KCL, but the setup requires a much larger investment from a developer; i.e. creating self-signed certificates, trust stores, etc. for use in their app. 

Please bring this control back. The developer community would greatly appreciate it.

## Expected Behavior
Using `com.amazonaws.sdk.disableCertChecking` as a system property disables SSL certificate validation.

## Current Behavior
Using `com.amazonaws.sdk.disableCertChecking` is not supported for any purpose.

## Possible Solution
Re-introduce `com.amazonaws.sdk.disableCertChecking` as a control for validating certificates. 

## Steps to Reproduce (for bugs)
* Start Localstack as a docker container. Here's a docker-compose file that could be used:
```
version: '2.2'
services:
  localstack-base:
    image: "${DOCKER_REPOSITORY}/localstack/localstack:0.9.1"
    environment:
      - "SERVICES=kinesis,cloudwatch,dynamodb"
      - "USE_SSL=true"
      - "DEFAULT_REGION=${LOCALSTACK_DEFAULT_REGION:-us-east-1}"
      - "KINESIS_PORT_EXTERNAL=${LOCALSTACK_KINESIS_PORT_EXTERNAL:-4568}"
      - "CLOUDWATCH_PORT_EXTERNAL=${LOCALSTACK_CLOUDWATCH_PORT_EXTERNAL:-4582}"
      - "DYNAMODB_PORT_EXTERNAL=${LOCALSTACK_CLOUDWATCH_PORT_EXTERNAL:-4569}"
```
* Set the `com.amazonaws.sdk.disableCertChecking` system property in your application
* Use `KinesisAsyncClient` against a localstack endpoint (typically https://localhost:4568)
* Observe SSL Handshake errors

## Context
I am trying to develop local integration tests for my application's kinesis producers and consumers. 

## Your Environment
* AWS Java SDK version used: `2.5.10`
* JDK version used: 8
* Operating System and version: MacOS - 10.14.3
